### ISSUE TITLE
bump to 0.4.5

### ISSUE THREAD

**Issue by s-ol** [paulbellamy/docker-urbit#2]
0.4.5 was released: https://github.com/urbit/urbit/releases/tag/v0.4.5

this includes my fix for the `.vere.lock` file that has been a problem for me using the docker image specifically because of autorestart and `docker stop` urbit signal behaviour.

**Comment by paulbellamy** [comment]
Hmm, doesn't seem to be a debian package yet. have opened https://github.com/urbit/urbit/issues/840

**Comment by s-ol** [comment]
@paulbellamy: there is one [hosted on the github releases](https://github.com/urbit/urbit/releases/tag/v0.4.5) (now) at least: 

    https://github.com/urbit/urbit/releases/download/v0.4.5/urbit_0.4.5-1_amd64.deb

**EDIT:** also `https://media.urbit.org/dist/debian/urbit_0.4.5-1_amd64.deb` seems valid, but I only diffed it against 0.4.3-1 from the same link.

**Comment by s-ol** [comment]
I added urbit/docs#182 to update the links and text

**Comment by paulbellamy** [comment]
Fixed by #4
